---
# A pre-commit hook for testing unreleased changes
# Run from tox with: `tox -e hook-min`
repos:
  - repo: local
    hooks:
      - id: mdformat
        name: mdformat-from-tox
        entry: mdformat
        args: [--strict-hooks]
        files: tests/pre-commit-test.md
        types: [markdown]
        language: system
